replicaCount: 2

image:
  repository: ghcr.io/kiryue0/mini-task-api
  tag: "v0.2"

service:
  type: NodePort
  port: 80
  targetPort: 9090
  nodePort: 30080

config:
  APP_NAME: "mini-task-api"
  PORT: "9090"

secret:
  SECRET_KEY: "super-gizli-deger-123"

ingress:
  host: mini-task-api.local
